name: TestProject CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-14
    name: Build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Select Xcode 16.2
      run: sudo xcode-select -s /Applications/Xcode_16.2.app
    - name: Build for iOS device
      run: |
        xcodebuild clean build \
        -project TestProject.xcodeproj \
        -scheme TestProject \
        -destination 'generic/platform=iOS' \
        IPHONEOS_DEPLOYMENT_TARGET=17.4 \
        CODE_SIGNING_ALLOWED=NO
  test:
    runs-on: macos-14
    name: Run Tests
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Select Xcode 16.2
      run: sudo xcode-select -s /Applications/Xcode_16.2.app
    - name: Install xcbeautify
      run: brew install xcbeautify
    - name: Run tests and generate report
      run: |
        set -o pipefail && \
        xcodebuild test \
        -project TestProject.xcodeproj \
        -scheme TestProject \
        -destination "platform=iOS Simulator,name=iPhone 15,OS=17.4" \
        -test-timeouts-enabled YES \
        IPHONEOS_DEPLOYMENT_TARGET=17.4 \
        CODE_SIGNING_ALLOWED=NO | \
        xcbeautify --renderer github-actions --report junit
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/reports/junit.xml
